# Generated by Django 2.2.5 on 2022-09-01 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('DICOMManagement', '0002_alter_dicomfile_sop_instance_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('error', models.IntegerField(choices=[(0, '已解析'), (202, '未初始化解析'), (403, '识别为非手骨图'), (415, '无法解析为图像')], default=202, verbose_name='错误类型')),
                ('brightness', models.IntegerField(default=100, verbose_name='亮度偏量（百分数）')),
                ('contrast', models.IntegerField(default=100, verbose_name='对比度偏量（百分数）')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('base_dcm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_DicomFile_base', to='DICOMManagement.DicomFile', verbose_name='DICOM信息基类')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_creater', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '骨龄用Dicom信息',
                'verbose_name_plural': '骨龄用Dicom信息',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('standard', models.CharField(choices=[('RUS', 'RUS-CHN标准'), ('CHN', 'CHN标准')], default='RUS', max_length=10, verbose_name='默认骨龄标准')),
                ('default_bone', models.CharField(choices=[('RUS_radius', 'RUS 桡骨'), ('RUS_ulna', 'RUS 尺骨'), ('RUS_first-metacarpal', 'RUS 第一掌骨'), ('RUS_third-metacarpal', 'RUS 第三掌骨'), ('RUS_fifth-metacarpal', 'RUS 第五掌骨'), ('RUS_first-proximal-phalange', 'RUS 第一近节指骨'), ('RUS_third-proximal-phalange', 'RUS 第三近节指骨'), ('RUS_fifth-proximal-phalange', 'RUS 第五近节指骨'), ('RUS_third-middle-phalange', 'RUS 第三中节指骨'), ('RUS_fifth-middle-phalange', 'RUS 第五中节指骨'), ('RUS_first-distal-phalange', 'RUS 第一远节指骨'), ('RUS_third-distal-phalange', 'RUS 第三远节指骨'), ('RUS_fifth-distal-phalange', 'RUS 第五远节指骨')], default='RUS_radius', max_length=100, verbose_name='默认骨骼')),
                ('shortcut', models.BooleanField(default=True, verbose_name='启用快捷键')),
                ('bone_order_RUS', models.CharField(default='Radius|Ulna|First Metacarpal|Third Metacarpal|Fifth Metacarpal|First Proximal Phalange|Third Proximal Phalange|Fifth Proximal Phalange|Third Middle Phalange|Fifth Middle Phalange|First Distal Phalange|Third Distal Phalange|Fifth Distal Phalange', max_length=500, verbose_name='RUS 骨骼排序')),
            ],
            options={
                'verbose_name': '偏好设置',
                'verbose_name_plural': '偏好设置',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('bone_age', models.FloatField(default=-1.0, verbose_name='骨龄')),
                ('allocated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='任务分配时间')),
                ('closed', models.BooleanField(default=False, verbose_name='已完成')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remarks', models.TextField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneAge_allocated_to', to=settings.AUTH_USER_MODEL, verbose_name='任务分配给')),
                ('dcm_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BoneAge.DicomFile', verbose_name='对应dcm')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneAge_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '骨龄判断结果',
                'verbose_name_plural': '骨龄判断结果',
            },
        ),
        migrations.CreateModel(
            name='BoneDetail',
            fields=[
                ('name', models.CharField(choices=[('Radius', '桡骨'), ('Ulna', '尺骨'), ('First Metacarpal', '第一掌骨'), ('First Proximal Phalange', '第一近节指骨'), ('First Distal Phalange', '第一远节指骨'), ('Third Metacarpal', '第三掌骨'), ('Third Proximal Phalange', '第三近节指骨'), ('Third Middle Phalange', '第三中节指骨'), ('Third Distal Phalange', '第三远节指骨'), ('Fifth Metacarpal', '第五掌骨'), ('Fifth Proximal Phalange', '第五近节指骨'), ('Fifth Middle Phalange', '第五中节指骨'), ('Fifth Distal Phalange', '第五远节指骨')], max_length=23, verbose_name='骨名')),
                ('level', models.IntegerField(choices=[(-1, '未评级'), (0, '0级'), (1, '1级'), (2, '2级'), (3, '3级'), (4, '4级'), (5, '5级'), (6, '6级'), (7, '7级'), (8, '8级'), (9, '9级'), (10, '10级'), (11, '11级'), (12, '12级'), (13, '13级'), (14, '14级')], default=-1, verbose_name='RUS-CHN 14阶评级')),
                ('error', models.IntegerField(choices=[(0, '正常'), (202, '未初始化解析'), (404, '无法定位')], default=202, verbose_name='定位状态')),
                ('center_x', models.FloatField(default=-1, verbose_name='中心点x')),
                ('center_y', models.FloatField(default=-1, verbose_name='中心点y')),
                ('width', models.FloatField(default=-1, verbose_name='宽度')),
                ('height', models.FloatField(default=-1, verbose_name='高度')),
                ('remarks', models.TextField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_BoneDetail_task', to='BoneAge.Task', verbose_name='所属骨龄记录')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneDetail_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '骨骼具体数据',
                'verbose_name_plural': '骨骼具体数据',
                'unique_together': {('task', 'name')},
            },
        ),
    ]
