# Generated by Django 4.0.3 on 2022-06-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boneage',
            name='closed_date',
            field=models.DateField(default=None, verbose_name='完成时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default=None, verbose_name='生日'),
            preserve_default=False,
        ),
    ]
