# Generated by Django 2.2.5 on 2022-09-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonedetail',
            old_name='bone_age_instance',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='bonedetail',
            unique_together={('task', 'name')},
        ),
    ]
