# Generated by Django 4.0.3 on 2022-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0002_boneage_closed_date_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boneage',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
