# Generated by Django 2.2.5 on 2022-09-01 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0002_auto_20220901_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonedetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_BoneDetail_task', to='BoneAge.Task', verbose_name='所属骨龄记录'),
        ),
    ]
