# Generated by Django 4.0.6 on 2023-02-08 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoneAge', '0002_task_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='standard',
            field=models.CharField(choices=[('RUS', 'RUS-CHN标准'), ('CHN', 'CHN标准')], default='RUS', max_length=10, verbose_name='任务标准'),
        ),
        migrations.AlterField(
            model_name='task',
            name='allocated_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分配时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneAge_allocated_to', to=settings.AUTH_USER_MODEL, verbose_name='分配给'),
        ),
    ]
