# Generated by Django 4.0.3 on 2022-06-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0003_alter_boneage_closed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_Id',
            new_name='Patient_ID',
        ),
    ]
