# Generated by Django 4.0.6 on 2023-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0003_task_standard_alter_task_allocated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonedetail',
            name='level',
            field=models.IntegerField(default=-1, verbose_name='骨骼评测（RUS等级/CHN分值）'),
        ),
    ]
