# Generated by Django 4.0.6 on 2023-02-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0004_alter_bonedetail_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonedetail',
            old_name='level',
            new_name='assessment',
        ),
    ]
