# Generated by Django 4.0.6 on 2022-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0005_auto_20220617_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boneage',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
