# Generated by Django 4.0.6 on 2023-02-08 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoneAge', '0005_rename_level_bonedetail_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_Task_allocated_to', to=settings.AUTH_USER_MODEL, verbose_name='分配给'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dcm_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_Task_affiliated_dcm', to='BoneAge.dicomfile', verbose_name='对应dcm'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_Task_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
    ]
