# Generated by Django 4.0.6 on 2022-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0006_alter_boneage_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='SOP_Instance_UID',
            field=models.CharField(default=None, max_length=64, verbose_name='SOP Instance UID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='Study_Date',
            field=models.DateField(default=None, verbose_name='Study Date'),
            preserve_default=False,
        ),
    ]
