# Generated by Django 4.0.6 on 2023-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0006_alter_task_allocated_to_alter_task_dcm_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='error',
            field=models.IntegerField(choices=[(0, '已解析'), (102, '分配中'), (202, '未初始化解析'), (403, '识别为非手骨图'), (415, '无法解析为图像')], default=202, verbose_name='错误类型'),
        ),
    ]
