# Generated by Django 4.0.6 on 2022-07-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0007_alter_dicomfile_sop_instance_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boneage',
            name='allocated_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务分配时间'),
        ),
    ]
