# Generated by Django 4.0.6 on 2022-07-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0008_boneage_allocated_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='SOP_Instance_UID',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SOP Instance UID'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='Study_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Study Date'),
        ),
    ]
