# Generated by Django 4.0.6 on 2023-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0008_alter_preference_default_bone'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='bone_order_CHN',
            field=models.CharField(default='Radius|First Metacarpal|Third Metacarpal|Fifth Metacarpal|First Proximal Phalange|Third Proximal Phalange|Fifth Proximal Phalange|Third Middle Phalange|Fifth Middle Phalange|First Distal Phalange|Third Distal Phalange|Fifth Distal Phalange|Capitate|Hamate', max_length=500, verbose_name='CHN 骨骼排序'),
        ),
        migrations.AlterField(
            model_name='bonedetail',
            name='name',
            field=models.CharField(choices=[('Radius', '桡骨'), ('Ulna', '尺骨'), ('First Metacarpal', '第一掌骨'), ('First Proximal Phalange', '第一近节指骨'), ('First Distal Phalange', '第一远节指骨'), ('Third Metacarpal', '第三掌骨'), ('Third Proximal Phalange', '第三近节指骨'), ('Third Middle Phalange', '第三中节指骨'), ('Third Distal Phalange', '第三远节指骨'), ('Fifth Metacarpal', '第五掌骨'), ('Fifth Proximal Phalange', '第五近节指骨'), ('Fifth Middle Phalange', '第五中节指骨'), ('Fifth Distal Phalange', '第五远节指骨'), ('Capitate', '头状骨'), ('Hamate', '钩骨')], max_length=23, verbose_name='骨名'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='default_bone',
            field=models.CharField(choices=[('radius', '桡骨'), ('ulna', '尺骨'), ('first-metacarpal', '第一掌骨'), ('third-metacarpal', '第三掌骨'), ('fifth-metacarpal', '第五掌骨'), ('first-proximal-phalange', '第一近节指骨'), ('third-proximal-phalange', '第三近节指骨'), ('fifth-proximal-phalange', '第五近节指骨'), ('third-middle-phalange', '第三中节指骨'), ('fifth-middle-phalange', '第五中节指骨'), ('first-distal-phalange', '第一远节指骨'), ('third-distal-phalange', '第三远节指骨'), ('fifth-distal-phalange', '第五远节指骨'), ('Capitate', '头状骨'), ('Hamate', '钩骨')], default='radius', max_length=100, verbose_name='默认骨骼'),
        ),
    ]
