# Generated by Django 4.0.6 on 2022-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0009_alter_dicomfile_sop_instance_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='age',
            field=models.FloatField(blank=True, null=True, verbose_name='当前检查实际年龄'),
        ),
    ]
