# Generated by Django 4.0.6 on 2022-08-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('BoneAge', '0010_dicomfile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('standard', models.CharField(choices=[('RUS', 'RUS-CHN标准'), ('CHN', 'CHN标准')], default='RUS', max_length=10, verbose_name='默认骨龄标准')),
                ('shortcut', models.BooleanField(default=True, verbose_name='快捷键')),
            ],
            options={
                'verbose_name': '偏好设置',
                'verbose_name_plural': '偏好设置',
            },
        ),
    ]
