# Generated by Django 4.0.6 on 2022-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0011_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='default_bone',
            field=models.CharField(choices=[('RUS_radius', 'RUS 桡骨'), ('RUS_ulna', 'RUS 尺骨'), ('RUS_first-metacarpal', 'RUS 第一掌骨'), ('RUS_third-metacarpal', 'RUS 第三掌骨'), ('RUS_fifth-metacarpal', 'RUS 第五掌骨'), ('RUS_first-proximal-phalange', 'RUS 第一近节指骨'), ('RUS_third-proximal-phalange', 'RUS 第三近节指骨'), ('RUS_fifth-proximal-phalange', 'RUS 第五近节指骨'), ('RUS_third-middle-phalange', 'RUS 第三中节指骨'), ('RUS_fifth-middle-phalange', 'RUS 第五中节指骨'), ('RUS_first-distal-phalange', 'RUS 第一远节指骨'), ('RUS_third-distal-phalange', 'RUS 第三远节指骨'), ('RUS_fifth-distal-phalange', 'RUS 第五远节指骨')], default='RUS_radius', max_length=100, verbose_name='默认骨骼'),
        ),
    ]
