# Generated by Django 4.0.6 on 2023-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0011_alter_dicomfile_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonedetail',
            name='error',
            field=models.IntegerField(choices=[(0, '正常'), (202, '未初始化解析'), (404, '无法定位')], default=202, verbose_name='错误类型'),
        ),
    ]
