# Generated by Django 4.0.6 on 2022-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0012_preference_default_bone'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='bone_order_RUS',
            field=models.CharField(default='radius ulna first-metacarpal third-metacarpal fifth-metacarpal first-proximal-phalange third-proximal-phalange fifth-proximal-phalange third-middle-phalange fifth-middle-phalange first-distal-phalange third-distal-phalange fifth-distal-phalange', max_length=500, verbose_name='RUS 骨骼排序'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='shortcut',
            field=models.BooleanField(default=True, verbose_name='启用快捷键'),
        ),
    ]
