# Generated by Django 4.0.6 on 2023-07-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DICOMManagement', '0003_alter_dicomfile_create_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoneAge', '0013_alter_bonedetail_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonedetail',
            name='assessment',
            field=models.IntegerField(default=-1, verbose_name='骨骼评测（等级）'),
        ),
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('query', models.CharField(max_length=1000, verbose_name='骨龄删选query')),
                ('interval', models.PositiveIntegerField(verbose_name='影像抓取间隔（分钟）')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('base_PACS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DICOMManagement.pacs', verbose_name='PACS基类')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_PACS_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_PACS_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '骨龄用PACS配置信息',
                'verbose_name_plural': '骨龄用PACS配置信息',
            },
        ),
    ]
