# Generated by Django 2.2.5 on 2022-08-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0014_alter_preference_bone_order_rus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomfile',
            name='age',
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='dcm',
            field=models.FileField(upload_to='DicomFiles/%Y/%m/', verbose_name='dcm源文件'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='dcm_to_image',
            field=models.ImageField(blank=True, null=True, upload_to='DicomFiles/%Y/%m/', verbose_name='dcm转图像'),
        ),
    ]
