# Generated by Django 4.0.6 on 2023-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0014_alter_bonedetail_assessment_pacs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomfile',
            options={'verbose_name': 'DICOM文件', 'verbose_name_plural': 'DICOM文件'},
        ),
        migrations.AlterModelOptions(
            name='pacs',
            options={'verbose_name': 'PACS配置信息', 'verbose_name_plural': 'PACS配置信息'},
        ),
    ]
