# Generated by Django 4.0.6 on 2022-08-20 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientManagement', '0001_initial'),
        ('DICOMManagement', '0001_initial'),
        ('BoneAge', '0015_auto_20220818_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='base_dcm',
            field=models.OneToOneField(null=True, blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_base', to='DICOMManagement.dicomfile', verbose_name='DICOM信息基类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='base_patient',
            field=models.OneToOneField(null=True, blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_base', to='PatientManagement.patient', verbose_name='患者信息基类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boneage',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneAge_allocated_to', to=settings.AUTH_USER_MODEL, verbose_name='任务分配给'),
        ),
        migrations.AlterField(
            model_name='boneage',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneAge_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AlterField(
            model_name='bonedetail',
            name='bone_age_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_BoneDetail_bone_age_instance', to='BoneAge.boneage', verbose_name='所属骨龄记录'),
        ),
        migrations.AlterField(
            model_name='bonedetail',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_BoneDetail_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_creater', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_Patient_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
