# Generated by Django 4.0.6 on 2022-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0016_dicomfile_base_dcm_patient_base_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='SOP_Instance_UID',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SOP Instance UID'),
        ),
    ]
