# Generated by Django 4.0.6 on 2022-08-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DICOMManagement', '0002_alter_dicomfile_sop_instance_uid'),
        ('PatientManagement', '0001_initial'),
        ('BoneAge', '0017_alter_dicomfile_sop_instance_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomfile',
            name='SOP_Instance_UID',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='Study_Date',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='dcm',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='dcm_to_image',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_ID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='base_dcm',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_DicomFile_base', to='DICOMManagement.dicomfile', verbose_name='DICOM信息基类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='base_patient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_base', to='PatientManagement.patient', verbose_name='患者信息基类'),
            preserve_default=False,
        ),
    ]
