# Generated by Django 4.2.1 on 2023-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0019_pacs_qr_end_time_pacs_qr_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs_qr',
            name='delay',
            field=models.PositiveIntegerField(default=10, help_text='影像从设备传送到PACS可能需要一定时间，通过该字段延迟抓取，否则可能会错过上传较慢的影像', verbose_name='PACS抓取延迟'),
        ),
    ]
