# Generated by Django 4.0.6 on 2022-08-31 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoneAge', '0020_alter_dicomfile_base_dcm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoneAge',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='dicomfile',
            options={'verbose_name': '骨龄用Dicom信息', 'verbose_name_plural': '骨龄用Dicom信息'},
        ),
    ]
