# Generated by Django 4.2.1 on 2023-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0020_pacs_qr_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacs_qr',
            name='delay',
        ),
        migrations.AddField(
            model_name='pacs_qr',
            name='confidence',
            field=models.PositiveIntegerField(default=80, help_text='当AI识别出百分之多少的手部骨骼时视为一张手骨图。低于该可信度的将视为错误影像，不会入库。默认80', verbose_name='可信度（%）'),
        ),
        migrations.AlterField(
            model_name='pacs_qr',
            name='interval',
            field=models.PositiveIntegerField(default=5, help_text='太长会PACS堵塞，太短可能会缺失传入PACS有延误的影像。建议时间：5~10分钟。默认5分钟', verbose_name='影像抓取间隔（分钟）'),
        ),
    ]
