# Generated by Django 4.0.6 on 2022-09-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0021_rename_boneage_task_alter_dicomfile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonedetail',
            old_name='bone_age_instance',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='bonedetail',
            unique_together={('task', 'name')},
        ),
    ]
