# Generated by Django 4.2.1 on 2023-08-27 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoneAge', '0022_alter_dicomfile_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs_qr',
            name='allocate_to',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='BoneAge_PACS_allocate_to', to=settings.AUTH_USER_MODEL, verbose_name='将推流影像分配给'),
            preserve_default=False,
        ),
    ]
