# Generated by Django 4.0.6 on 2022-09-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0022_rename_bone_age_instance_bonedetail_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonedetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoneAge_BoneDetail_task', to='BoneAge.task', verbose_name='所属骨龄记录'),
        ),
    ]
