# Generated by Django 4.2.1 on 2023-08-28 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0023_pacs_qr_allocate_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='error',
            field=models.IntegerField(choices=[(0, '已解析'), (102, '处理中'), (202, '未初始化解析'), (403, '识别为非手骨图'), (422, '无法解析为图像')], default=202, verbose_name='错误类型'),
        ),
        migrations.AlterField(
            model_name='pacs_qr',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 0), null=True, verbose_name='每日结束时间'),
        ),
        migrations.AlterField(
            model_name='pacs_qr',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(6, 0), null=True, verbose_name='每日启动时间'),
        ),
    ]
