# Generated by Django 4.2.1 on 2023-08-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('BoneAge', '0024_alter_dicomfile_error_alter_pacs_qr_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACS_QR_Log',
            fields=[
                ('StudyDate', models.CharField(max_length=8, verbose_name='所查日期')),
                ('StudyTime', models.CharField(max_length=17, verbose_name='所查时间段')),
                ('retrieved_instances', models.CharField(max_length=5000, verbose_name='抓获结果（orthanc id）')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('pacs_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoneAge.pacs_qr', verbose_name='配置')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_q.schedule', verbose_name='所属任务')),
            ],
        ),
    ]
