# Generated by Django 4.2.1 on 2023-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0025_pacs_qr_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs_qr_log',
            name='migrated',
            field=models.BooleanField(default=False, verbose_name='是否已迁移至系统'),
        ),
    ]
