# Generated by Django 4.2.1 on 2023-08-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0026_pacs_qr_log_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='error',
            field=models.IntegerField(choices=[(0, '已解析'), (102, '处理中'), (202, '未初始化解析'), (403, '识别为非手骨图')], default=202, verbose_name='错误类型'),
        ),
        migrations.AlterField(
            model_name='pacs_qr',
            name='interval',
            field=models.PositiveIntegerField(default=5, help_text='太长会传输文件过多导致PACS堵塞，太短可能会缺失传入PACS有延误的影像。建议时间：5~10分钟。默认5分钟', verbose_name='影像抓取间隔（分钟）'),
        ),
    ]
