# Generated by Django 4.2.1 on 2023-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0027_alter_dicomfile_error_alter_pacs_qr_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs_qr',
            name='standard',
            field=models.CharField(choices=[('RUS', 'RUS-CHN标准'), ('CHN', 'CHN标准')], default='CHN', max_length=10, verbose_name='骨龄标准'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='error',
            field=models.IntegerField(choices=[(0, '正常'), (102, '文件处理中'), (403, '识别为非手骨图')], default=202, verbose_name='错误类型'),
        ),
    ]
