# Generated by Django 4.2.1 on 2023-10-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('BoneAge', '0029_alter_pacs_qr_log_pacs_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs_qr_log',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule', verbose_name='所属任务'),
        ),
    ]
