# Generated by Django 4.2.1 on 2023-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoneAge', '0030_alter_pacs_qr_log_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs_qr_log',
            name='retrieved_instances',
            field=models.TextField(verbose_name='抓获结果（orthanc id）'),
        ),
    ]
