# Generated by Django 4.2.4 on 2023-11-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("BoneAge", "0031_alter_pacs_qr_log_retrieved_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="allocator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="BoneAge_Task_allocator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="任务分派者",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dicomfile",
            name="error",
            field=models.IntegerField(
                choices=[
                    (0, "正常"),
                    (102, "文件处理中"),
                    (403, "识别为非手骨图"),
                    (500, "结算骨龄出错，患者性别未知或其他代码问题"),
                ],
                default=202,
                verbose_name="错误类型",
            ),
        ),
    ]
