# Generated by Django 4.2.4 on 2023-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0032_task_allocator_alter_dicomfile_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="bone_order_CHN",
            field=models.CharField(
                default="Radius|First Metacarpal|Third Metacarpal|Fifth Metacarpal|First Proximal Phalange|Third Proximal Phalange|Fifth Proximal Phalange|Third Middle Phalange|Fifth Middle Phalange|First Distal Phalange|Third Distal Phalange|Fifth Distal Phalange|Capitate|Hamate",
                max_length=500,
                verbose_name="CHN 骨骼排序",
            ),
        ),
    ]
