# Generated by Django 4.2.4 on 2023-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0033_alter_preference_bone_order_chn"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "进行中"),
                    ("reported", "检错中"),
                    ("verifying", "审核中"),
                    ("finished", "已完成"),
                ],
                default="processing",
                max_length=10,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="closed",
            field=models.BooleanField(default=False, verbose_name="已完结"),
        ),
    ]
