# Generated by Django 4.2.4 on 2023-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0034_task_status_alter_task_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="default_bone",
        ),
        migrations.AddField(
            model_name="preference",
            name="chn_default_bone",
            field=models.CharField(
                choices=[
                    ("radius", "桡骨"),
                    ("first-metacarpal", "第一掌骨"),
                    ("third-metacarpal", "第三掌骨"),
                    ("fifth-metacarpal", "第五掌骨"),
                    ("first-proximal-phalange", "第一近节指骨"),
                    ("third-proximal-phalange", "第三近节指骨"),
                    ("fifth-proximal-phalange", "第五近节指骨"),
                    ("third-middle-phalange", "第三中节指骨"),
                    ("fifth-middle-phalange", "第五中节指骨"),
                    ("first-distal-phalange", "第一远节指骨"),
                    ("third-distal-phalange", "第三远节指骨"),
                    ("fifth-distal-phalange", "第五远节指骨"),
                    ("capitate", "头状骨"),
                    ("hamate", "钩骨"),
                ],
                default="radius",
                max_length=100,
                verbose_name="CHN默认骨骼",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="rus_default_bone",
            field=models.CharField(
                choices=[
                    ("radius", "桡骨"),
                    ("first-metacarpal", "第一掌骨"),
                    ("third-metacarpal", "第三掌骨"),
                    ("fifth-metacarpal", "第五掌骨"),
                    ("first-proximal-phalange", "第一近节指骨"),
                    ("third-proximal-phalange", "第三近节指骨"),
                    ("fifth-proximal-phalange", "第五近节指骨"),
                    ("third-middle-phalange", "第三中节指骨"),
                    ("fifth-middle-phalange", "第五中节指骨"),
                    ("first-distal-phalange", "第一远节指骨"),
                    ("third-distal-phalange", "第三远节指骨"),
                    ("fifth-distal-phalange", "第五远节指骨"),
                    ("ulna", "尺骨"),
                ],
                default="radius",
                max_length=100,
                verbose_name="CHN默认骨骼",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="standard",
            field=models.CharField(
                choices=[("RUS", "RUS-CHN标准"), ("CHN", "CHN标准")],
                default="RUS",
                max_length=10,
                verbose_name="主页默认骨龄标准",
            ),
        ),
    ]
