# Generated by Django 4.2.4 on 2023-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0036_alter_preference_rus_default_bone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="standard",
            field=models.CharField(
                choices=[("RUS", "RUS-CHN标准"), ("CHN", "CHN标准")],
                default="CHN",
                max_length=10,
                verbose_name="主页默认骨龄标准",
            ),
        ),
    ]
