# Generated by Django 4.2.4 on 2023-12-17 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0038_preference_bone_age_copy_format_chn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="marked",
        ),
    ]
