# Generated by Django 4.2.4 on 2023-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0040_alter_task_status_tasklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="备注"
            ),
        ),
    ]
