# Generated by Django 4.2.4 on 2023-12-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0041_alter_task_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="task",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BoneAge_TaskLog_task",
                to="BoneAge.task",
                verbose_name="所属任务",
            ),
            preserve_default=False,
        ),
    ]
