# Generated by Django 4.2.4 on 2023-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0042_tasklog_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("create", "新建任务"),
                    ("update", "更新内容"),
                    ("report", "提交报错审核"),
                    ("submit", "提交完成审核"),
                    ("verify", "审核通过"),
                    ("finish", "结束任务"),
                    ("delete", "删除任务"),
                    ("reopen", "重开任务"),
                ],
                max_length=10,
                verbose_name="操作",
            ),
        ),
    ]
