# Generated by Django 4.2.4 on 2023-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BoneAge", "0043_alter_tasklog_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("create", "新建任务"),
                    ("update", "更新内容"),
                    ("report", "报错待审"),
                    ("submit", "完成待审"),
                    ("withdraw", "撤销提交"),
                    ("reject", "审核不通过"),
                    ("verify", "审核通过"),
                    ("finish", "快捷完成任务"),
                    ("delete", "删除任务"),
                    ("reopen", "重开任务"),
                ],
                max_length=10,
                verbose_name="操作",
            ),
        ),
    ]
