# Generated by Django 4.0.6 on 2023-07-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PatientManagement_Patient_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
    ]
