# Generated by Django 4.2.1 on 2023-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0002_alter_patient_modify_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女'), ('Other', '其他')], max_length=6, verbose_name='性别'),
        ),
    ]
