# Generated by Django 4.0.6 on 2022-08-20 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('dcm', models.FileField(upload_to='DicomFiles/%Y/%m/', verbose_name='dcm源文件')),
                ('dcm_to_image', models.ImageField(blank=True, null=True, upload_to='DicomFiles/%Y/%m/', verbose_name='dcm转图像')),
                ('SOP_Instance_UID', models.CharField(blank=True, max_length=64, null=True, verbose_name='SOP Instance UID')),
                ('Study_Date', models.DateField(blank=True, null=True, verbose_name='Study Date')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicomfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicomfile_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PatientManagement.patient', verbose_name='所属患者')),
            ],
            options={
                'verbose_name': 'Dicom文件',
                'verbose_name_plural': 'Dicom文件',
            },
        ),
    ]
