# Generated by Django 4.0.6 on 2023-07-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DICOMManagement', '0002_alter_dicomfile_sop_instance_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DICOMManagement_DicomFile_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='modify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DICOMManagement_DicomFile_modifier', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('local_ip', models.GenericIPAddressField(verbose_name='本机IP')),
                ('local_port', models.PositiveIntegerField(unique=True, verbose_name='本机Orthanc端口')),
                ('local_http_port', models.PositiveIntegerField(unique=True, verbose_name='本机Orthanc网页端口')),
                ('local_AET', models.CharField(max_length=50, verbose_name='本机实体名')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='远程PACS IP')),
                ('remote_port', models.PositiveIntegerField(verbose_name='远程PACS 端口号')),
                ('remote_AET', models.CharField(max_length=50, verbose_name='远程实体名')),
                ('config_path', models.CharField(max_length=1000, verbose_name='配置文件路径')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Running', '正常运行'), ('Suspending', '挂起'), ('Closed', '关闭')], max_length=50)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DICOMManagement_PACS_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'PACS服务器',
                'verbose_name_plural': 'PACS服务器',
            },
        ),
    ]
