# Generated by Django 4.0.6 on 2023-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DICOMManagement', '0003_alter_dicomfile_create_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomfile',
            options={'verbose_name': 'DICOM文件', 'verbose_name_plural': 'DICOM文件'},
        ),
    ]
