# Generated by Django 4.2.1 on 2023-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DICOMManagement', '0007_dicomfile_window_center_dicomfile_window_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='Study_Time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Study Time'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='Study_Date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Study Date'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='Window_Center',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Window Center'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='Window_Width',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Window Width'),
        ),
    ]
