# Generated by Django 4.2.1 on 2023-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DICOMManagement', '0009_alter_dicomfile_study_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='dcm',
            field=models.FileField(max_length='1000', upload_to='DicomFiles/%Y/%m/', verbose_name='dcm源文件'),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='dcm_to_image',
            field=models.ImageField(blank=True, max_length='1000', null=True, upload_to='DicomFiles/%Y/%m/', verbose_name='dcm转图像'),
        ),
    ]
